# -*- coding: utf-8 -*-
"""mnist-classification.ipynb

Automatically generated by Colaboratory.

Original file is located at
    https://colab.research.google.com/drive/1SqETl3Zi1EEesdJfEv6_QimB-M-YjKGx
"""

from tensorflow import keras
from tensorflow.keras import Sequential
from tensorflow.keras.layers import Dense,Flatten

# Get data from predefined dataset of keras library
(X_train,y_train),(X_test,y_test) = keras.datasets.mnist.load_data() 

# Image's pixels must be between 0-1, so modal can predict more accurate
X_train = X_train/255
X_test = X_test/255

# Modal compile properties
model = Sequential()
model.add(Flatten(input_shape=(28,28)))
model.add(Dense(128,activation='relu'))
model.add(Dense(32,activation='relu'))
model.add(Dense(10,activation='softmax'))

model.summary()

model.compile(loss='sparse_categorical_crossentropy',optimizer='Adam',metrics=['accuracy'])

history = model.fit(X_train,y_train,epochs=25,validation_split=0.2)

model.save('mnist-latest.h5') # save model so we can use later
